export const people = [
  {
    id: '1',
    nome: 'Macherie Hourne',
    jogo: 'War of the Visions',
    classe: 'Cleric',
    elemento: 'Holy',
    portrait: '/portrait/macherie_hourne.jpg',
    img_elemento: '/element/holy.jpg',
  },
  {
    id: '2',
    nome: 'Agrias Oaks',
    jogo: 'Final Fantasy Tactics',
    classe: 'Holy Knight',
    elemento: 'Ice',
    portrait: '/portrait/agrias_oaks.jpg',
    img_elemento: '/element/ice.jpg',
  },
  {
    id: '3',
    nome: 'Cidolfus Orlandeau',
    jogo: 'Final Fantasy Tactics',
    classe: 'Sword Saint',
    portrait: '/portrait/cidoulfus_orlandeau.jpg',
    img_elemento: '/element/thunder.jpg',
  },
  {
    id: '4',
    nome: 'Mustadio Bunanza',
    jogo: 'Final Fantasy Tactics',
    classe: 'Machinist',
    portrait: '/portrait/mustadio.jpg',
    img_elemento: '/element/earth.jpg',
  },
];